/**
 * Snapshot types for the demo Assistant API.
 * Cards are generated by Abel `npm run assistant:export-kb`. Do not author a second KB here.
 */
import type { FrontendKnowledgeBundle, FrontendKnowledgeCard } from './types';

export type ServerKnowledgeCard = FrontendKnowledgeCard & {
  businessRules: string[];
};

export type ServerKnowledgeRule = {
  id: string;
  title: string;
  statement: string;
};

export type ServerKnowledgeBundle = FrontendKnowledgeBundle & {
  rules: ServerKnowledgeRule[];
  cards: ServerKnowledgeCard[];
};
